name: Scheduled Vercel Deploy
on:
  schedule:
    - cron: '0 2 * * *' # 每天凌晨2点（UTC）自动触发
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VERCEL_DEPLOY_HOOK: ${{ secrets.VERCEL_DEPLOY_HOOK }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Trigger Vercel Deploy
        run: |
          curl -X POST "$VERCEL_DEPLOY_HOOK" # 使用 env 变量
